name: Create prerelease on PR open
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions: {}

jobs:
  prerelease:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          persist-credentials: true # zizmor: ignore[artipacked]

      - name: Create prerelease
        uses: partly-cloud/create-release-action@4f7648584e83f014059cd9fc200cff560628de3f # 0.1.0
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          pr_number: ${{ github.event.pull_request.number }}
          prerelease: "true"
